- name: first settings for development
  hosts: devs
  user: ec2-user
  sudo: yes
  vars_files:
    # must define => user_name, user_password(hashed), ssh_port, hostname
    - vars/external_vars.yml

  tasks:
    - name: change SSH port
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#Port " line="Port {{ ssh_port }}" state=present
      notify: restart sshd

    - name: create iptables
      template: src=iptables.j2 dest=/etc/sysconfig/iptables
    # when: ansible_distribution_major_version == "6"

    # - name: setting firewalld for ssh
    #   firewalld: zone=public port={{ ssh_port }}/tcp state=enabled permanent=true immediate=yes
    #   notify: restart firewalld
    #   when: ansible_distribution_major_version == "7"

    - name: create user
      user: name={{ user_name }} password={{ user_password }} groups=wheel

    - name: allow wheel users to sudo
      # NOTE: Because of the ': ' on the line, fully quote or use {{':'}}.
      lineinfile: dest=/etc/sudoers regexp="^#\s*(%wheel\s+ALL=\(ALL\)\s+NOPASSWD{{':'}}\s+ALL)" line="\1" backrefs=yes state=present

    - name: define hostname
      hostname: name={{ hostname }}

    - name: create .ssh dir for the new user
      file: path=/home/develop/.ssh state=directory owner={{ user_name }} group={{ user_name }} mode=700

    # - name: copy authorized keys
    #   copy: src=/root/.ssh/authorized_keys dest=/home/develop/.ssh/authorized_keys owner={{ user_name }} group={{ user_name }} mode=600

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted

    - name: restart iptable
      service: name=iptables state=restarted

    - name: restart firewalld
      service: name=firewalld state=restarted

